name: SCALA_CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

#  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'sbt'
      - name: Run tests
        run: sbt test

#      - name: Debug Output
#        run: |
#            echo "Access Token: ${{ secrets.SCALA_CI }}"
#            git config --list
#            git remote -v
#
#      - name: Push to GitHub with Access Token
#        run: |
#          git config --global user.email "paulmunyao094@gmail.com"
#          git config --global user.name "paulmunyao"
#          git remote set-url origin https://github.com/paulmunyao/Knight-s-Tour.git
#          git push origin master
        env:
          ACCESS_TOKEN: ${{ secrets.SCALA_CI }}

